// scripts/generate-sdk/generate-barrel.mjs
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const OUTPUT_DIR = join(import.meta.dirname, "../../generated");

/**
 * Generate barrel export files (index.ts) for types, api, and root.
 */
export function generateBarrelExports(groups) {
	const sortedFileNames = Object.keys(groups).sort();

	// generated/types/index.ts
	const typesBarrel = [
		"// Auto-generated by ClickUp SDK Generator",
		"// Do not edit manually\n",
		...sortedFileNames.map((f) => `export * from "./${f}";`),
		"",
	].join("\n");

	mkdirSync(join(OUTPUT_DIR, "types"), { recursive: true });
	writeFileSync(join(OUTPUT_DIR, "types/index.ts"), typesBarrel);

	// generated/api/index.ts
	const apiBarrel = [
		"// Auto-generated by ClickUp SDK Generator",
		"// Do not edit manually\n",
		...sortedFileNames.map((f) => `export * from "./${f}.api";`),
		"",
	].join("\n");

	mkdirSync(join(OUTPUT_DIR, "api"), { recursive: true });
	writeFileSync(join(OUTPUT_DIR, "api/index.ts"), apiBarrel);

	// generated/index.ts
	const rootBarrel = [
		"// Auto-generated by ClickUp SDK Generator",
		"// Do not edit manually\n",
		`export * from "./types";`,
		`export * from "./api";`,
		"",
	].join("\n");

	writeFileSync(join(OUTPUT_DIR, "index.ts"), rootBarrel);

	console.log(`  Generated 3 barrel files (${sortedFileNames.length} modules each)`);
}
