// scripts/generate-sdk/generate-types.mjs
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const OUTPUT_DIR = join(import.meta.dirname, "../../generated/types");

/**
 * Convert a string to PascalCase.
 */
function toPascalCase(str) {
	return str
		.replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase())
		.replace(/^(.)/, (c) => c.toUpperCase());
}

/**
 * Clean up a name for use as a TypeScript identifier.
 * Strips common verbose prefixes from v3 schema names.
 */
function cleanTypeName(name) {
	// V3 names like "ChatPublicApiChatChannelsControllerGetChatChannels200Response"
	// Strip the controller/module prefix pattern
	return name
		.replace(/PublicApi\w+Controller/, "")
		.replace(/^\d+/, ""); // Remove leading numbers
}

/**
 * Convert an OpenAPI schema to TypeScript type string.
 */
function schemaToType(schema, indent = "\t", context = {}) {
	if (!schema) return "unknown";

	// Handle allOf (intersection)
	if (schema.allOf) {
		const parts = schema.allOf.map((s) => schemaToType(s, indent, context));
		return parts.join(" & ");
	}

	// Handle oneOf / anyOf (union)
	if (schema.oneOf || schema.anyOf) {
		const variants = schema.oneOf || schema.anyOf;
		const parts = variants.map((s) => schemaToType(s, indent, context));
		return parts.join(" | ");
	}

	// Handle enum
	if (schema.enum) {
		return schema.enum.map((v) => (typeof v === "string" ? `"${v}"` : String(v))).join(" | ");
	}

	// Handle $ref that wasn't resolved (shouldn't happen but safety)
	if (schema.$ref) {
		return "unknown";
	}

	const type = schema.type;

	// Handle nullable
	const nullable = schema.nullable ? " | null" : "";

	if (type === "string") {
		if (schema.format === "date-time") return `string${nullable}`;
		if (schema.format === "binary") return `Blob${nullable}`;
		return `string${nullable}`;
	}

	if (type === "number" || type === "integer") return `number${nullable}`;
	if (type === "boolean") return `boolean${nullable}`;

	if (type === "array") {
		const itemType = schemaToType(schema.items, indent, context);
		return `Array<${itemType}>${nullable}`;
	}

	if (type === "object" || schema.properties) {
		return objectToInlineType(schema, indent, context);
	}

	// No type specified - fallback
	if (!type && !schema.properties) return "unknown";

	return `unknown${nullable}`;
}

/**
 * Convert an object schema to inline TypeScript type.
 */
function objectToInlineType(schema, indent = "\t", context = {}) {
	const props = schema.properties;
	if (!props || Object.keys(props).length === 0) {
		if (schema.additionalProperties) {
			const valType = schemaToType(schema.additionalProperties, indent, context);
			return `Record<string, ${valType}>`;
		}
		return "Record<string, unknown>";
	}

	const required = new Set(schema.required || []);
	const lines = [];
	const nextIndent = indent + "\t";

	for (const [propName, propSchema] of Object.entries(props)) {
		const opt = required.has(propName) ? "" : "?";
		const propType = schemaToType(propSchema, nextIndent, context);

		if (propSchema.description) {
			lines.push(`${indent}/** ${propSchema.description} */`);
		}
		lines.push(`${indent}${safePropName(propName)}${opt}: ${propType};`);
	}

	const nullable = schema.nullable ? " | null" : "";
	return `{\n${lines.join("\n")}\n${indent.slice(0, -1)}}${nullable}`;
}

/**
 * Make a property name safe for TypeScript.
 */
function safePropName(name) {
	if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name)) return name;
	return `"${name}"`;
}

/**
 * Generate type declarations for a group's endpoints.
 */
function generateGroupTypes(group) {
	const lines = [];
	const generatedNames = new Set();

	lines.push(`// Auto-generated by ClickUp SDK Generator`);
	lines.push(`// Group: ${group.tag}`);
	lines.push(`// Do not edit manually\n`);

	for (const endpoint of group.endpoints) {
		const baseName = endpoint.operationIdPascal;

		// Query params type
		const queryParams = endpoint.parameters.filter((p) => p.in === "query");
		if (queryParams.length > 0) {
			const typeName = `${baseName}Params`;
			if (!generatedNames.has(typeName)) {
				generatedNames.add(typeName);
				lines.push(`export interface ${typeName} {`);
				for (const param of queryParams) {
					if (param.description) {
						lines.push(`\t/** ${param.description} */`);
					}
					const opt = param.required ? "" : "?";
					const paramType = schemaToType(param.schema, "\t\t");
					lines.push(`\t${safePropName(param.name)}${opt}: ${paramType};`);
				}
				lines.push(`}\n`);
			}
		}

		// Request body type
		if (endpoint.requestBody?.schema) {
			const typeName = `${baseName}Request`;
			if (!generatedNames.has(typeName)) {
				generatedNames.add(typeName);
				const schema = endpoint.requestBody.schema;
				if (schema.properties) {
					lines.push(`export interface ${typeName} ${objectToInlineType(schema, "\t")}\n`);
				} else {
					const typeStr = schemaToType(schema, "\t");
					lines.push(`export type ${typeName} = ${typeStr};\n`);
				}
			}
		}

		// Response types (2xx)
		for (const [code, resp] of Object.entries(endpoint.responses)) {
			if (!resp.schema) continue;

			const suffix = Object.keys(endpoint.responses).length > 1 ? `${code}Response` : "Response";
			const typeName = `${baseName}${suffix === "Response" ? "Response" : suffix}`;
			if (!generatedNames.has(typeName)) {
				generatedNames.add(typeName);
				const schema = resp.schema;
				if (schema.properties) {
					lines.push(`export interface ${typeName} ${objectToInlineType(schema, "\t")}\n`);
				} else {
					const typeStr = schemaToType(schema, "\t");
					lines.push(`export type ${typeName} = ${typeStr};\n`);
				}
			}
		}
	}

	return lines.join("\n");
}

/**
 * Generate TypeScript type files for all groups.
 */
export function generateTypes(groups) {
	mkdirSync(OUTPUT_DIR, { recursive: true });

	let totalTypes = 0;
	for (const [fileName, group] of Object.entries(groups).sort(([a], [b]) => a.localeCompare(b))) {
		const content = generateGroupTypes(group);
		const filePath = join(OUTPUT_DIR, `${fileName}.ts`);
		writeFileSync(filePath, content);

		const typeCount = (content.match(/^export (interface|type)/gm) || []).length;
		totalTypes += typeCount;
	}

	console.log(`  Generated ${totalTypes} types across ${Object.keys(groups).length} files`);
}
